name: Daily Tweet from GitHub Activity

on:
  schedule:
    # Runs every day at 7:00 PM IST (1:30 PM UTC)
    - cron: '30 13 * * *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  generate-and-post-tweet:
    runs-on: ubuntu-latest
    environment: main 
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy python-dotenv google-generativeai requests
        
    - name: Generate and post tweet
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        python main.py
